version: '3.8'

services:
  neo4j:
    image: neo4j:5.18
    container_name: neo4j
    ports:
      - "7474:7474"   # HTTP browser
      - "7687:7687"   # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/test1234
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
    container_name: backend
    command: python -m src.app.main
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - redis
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test1234
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    working_dir: /app

volumes:
  neo4j_data:
  redis_data:
