version: '3.8'

services:
  neo4j:
    image: neo4j:5.18
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - aurasense-network
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aurasense-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  graphiti:
    image: zepai/graphiti:latest
    container_name: graphiti
    ports:
      - "${GRAPHITI_PORT:-8080}:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - GRAPHITI_DB_PATH=/data/graphiti.db
    volumes:
      - graphiti_data:/data
    networks:
      - aurasense-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aurasense-backend
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      - neo4j
      - redis
      - graphiti
    env_file:
      - .env
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - REDIS_URL=redis://redis:6379
      - GRAPHITI_HOST=graphiti
      - HOST=0.0.0.0
    networks:
      - aurasense-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  neo4j_data:
  neo4j_logs:
  redis_data:
  graphiti_data:

networks:
  aurasense-network:
    driver: bridge
